version: "3.9"

services:

  streamlit:

    build: .

    container_name: techseo_streamlit

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8501:8501"

    volumes:
      - .:/app
      - /home/madina/techseo-data:/app/data

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  api:

    build: .

    container_name: techseo_api

    restart: unless-stopped

    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - /home/madina/techseo-data:/app/data

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:

    image: redis:7

    container_name: techseo_redis

    restart: unless-stopped

    ports:
      - "6379:6379"

  celery:

    build: .

    container_name: techseo_celery

    restart: unless-stopped

    command: celery -A tasks.audit_tasks worker --loglevel=info

    env_file:
      - .env

    volumes:
      - .:/app
      - /home/madina/techseo-data:/app/data

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:

    build: .

    container_name: techseo_celery_beat

    restart: unless-stopped

    command: celery -A tasks.audit_tasks beat --loglevel=info

    env_file:
      - .env

    volumes:
      - .:/app
      - /home/madina/techseo-data:/app/data

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
