from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4

from services.score_service import get_score_risk


# ==================================================
# SUMMARY
# ==================================================

def generate_report_summary(score, errors_count):
    score_risk = get_score_risk(score)

    return f"""
SEO Health Score: {score}/100

Количество ошибок: {errors_count}

Общий вывод:
{score_risk["report_status"]}
"""


# ==================================================
# PDF REPORT
# ==================================================

def generate_pdf_report(url, score, errors_count, recommendations):
    filename = "seo_report.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("TechSEO Monitor Report", styles["Title"]))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(f"<b>Сайт:</b> {url}", styles["BodyText"]))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"<b>SEO Health Score:</b> {score}/100", styles["BodyText"]))
    elements.append(Paragraph(f"<b>Количество ошибок:</b> {errors_count}", styles["BodyText"]))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Рекомендации", styles["Heading2"]))

    for recommendation in recommendations:
        elements.append(Paragraph(f"• {recommendation}", styles["BodyText"]))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by TechSEO Monitor", styles["Italic"]))
    doc.build(elements)

    return filename
